### ISSUE TITLE
Tradepile

### ISSUE THREAD

**Issue by Lockedd** [trydis/FIFA-Ultimate-Team-Toolkit#140]
When I try to retrieve the trade pile with:

var tradePileRespone = await client.GetTradePileAsync();

I get:

An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Error converting value {null} to type 'System.Boolean'. Path 'auctionInfo[0].tradeOwner', line 1, position 1188.

What could be the problem?

**Comment by xtheokles** [comment]
Hey Lockedd! I had the same problem, I don't know if it's the best way to do it, but at least it's working for me since 3 days ago!

Just change in AuctionInfo.cs this line
public boolean TradeOwner { get; set; }
by this:
public object TradeOwner { get; set; }

Object accepts null values so it isn't crashing everytime you deal with tradepile.

**Comment by eupantof** [comment]
I would recommend in using public bool? TradeOwner { get; set; }
The question mark permits null for not-nullable data types, like boolean is here.

**Comment by Lockedd** [comment]
Thanks @xtheokles
