### ISSUE TITLE
Autobuyer Project

### ISSUE THREAD

**Issue by Lululuz** [trydis/FIFA-Ultimate-Team-Toolkit#195]
Hey everyone,

I released my AB to public. Feel free to use, contribute, improve or just don't care about it.

https://github.com/Lululuz/FutBud

If you can't build the source for any reason you can download the latest binary at http://futbud.com/

I'm not a professional programmer so don't expect super awesome code :)

At this point, thanks again to trydis for the toolkit.

It's licensed under GPL which means you can do almost everything whith it (no commercial stuff though)

**Comment by trydis** [comment]
:+1:

**Comment by D4NNY1000000** [comment]
Its clean!

**Comment by watcherize** [comment]
:+1:

**Comment by xtheokles** [comment]
Let's try it :) Good job!

**Comment by captainstaph** [comment]
Wow, really nice job and not a lot to complain about in the code either. You covered all the details, thanks a lot. I did have an issue bidding on low value players, looks like the starting bid calculation was incorrect when listing won auctions... I think it was for players under 1000 (yeah I started a new account because I am afraid of risking my first one- so low end moves to start with).

So an open question: I left the bid timing at 3 seconds (default). After about 5 hours I was banned from searches, and this morning I remain banned. What setting do you guys find to be optimal?

**Comment by DarkVador101** [comment]
thanks, your code looks nice and clean. I don't play FUT but I will look into your code further to see if I can implement any new features then I will PM you with the code.

**Comment by kostyan5** [comment]
I wrote my own autobuyer in Swift for OSX. If I price search 1 per second, I get temp ban (error message) after exactly 1000 tries.

There seems to be a hard limit on short term (perhaps per hour) and long term (per day). It would be nice if we could figure out what it is.

**Comment by tringler** [comment]
@Lululuz - You should close the issue, because of no answer since about a month. Thanks!

**Comment by DarkVador101** [comment]
lol, he is now charging a subscription for other's people work.
