### ISSUE TITLE
Unknown Error (494)

### ISSUE THREAD

**Issue by drawalex** [trydis/FIFA-Ultimate-Team-Toolkit#287]
I have the tool working with one account and i have just logged in and received the following error.
Unknown EA error, please report on GitHub - Code: 494

**Comment by Majed93** [comment]
Can you access the transfer market normally on the web app?

**Comment by proeben** [comment]
494 means club is not tf mkt enabled

Von meinem iPhone gesendet

**Comment by Nicorad** [comment]
Hi,

I have the same error with 2 accounts... I already read that 494 is caused because the tf mkt is disable, but I can use it since 2 weeks on the web app...

**Comment by artielange** [comment]
I think you should check again because 494 means definitely that transfer market is disabled for account. Check the webapp (clear cookies and such) and you should see the "continue playing to access transfer market"

Speaking of this condition.. It seems pretty irregular. I played 5 games on one account and a day later the account worked fine on webapp

I played 5 games and waited a few days on another account and it still was not enabled. I had to play a couple more games for the account to work on webapp. I wonder if this number of games depends on the number of accounts per console, age of the account, etc.. But it surely isn't just the number of games played
