### ISSUE TITLE
Searching players has no results

### ISSUE THREAD

**Issue by lkuklis** [trydis/FIFA-Ultimate-Team-Toolkit#305]
Hi, 
I know there was a issue raised (https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/issues/282) but it was closed without any explanation so I want to ask if there is as issue related to searching players? I can get results only when I pass ResourceId to search parameters. 

When I search for gold cards I get "Status = WaitingForActivation" in PerformRequestAsync method of SearchRequest class.

So is WebApp see my account as not activated? Even I can do everything by WebApp or Companion App or is there problem with searching players?

**Comment by trydis** [comment]
One reason is certainly because i wasn't paying enough attention when merging a pull request a while ago.

It used to only use the ResourceId if it was set, but as you can see [here](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/blob/master/UltimateTeam.Toolkit/Parameters/PlayerSearchParameters.cs#L41) it will use it no matter what at the moment.

I guess there have been few complaints because most people search for specific players.

Until i fix it or someone sends a PR, you'll have to pull down the source code and change it.

**Comment by lkuklis** [comment]
Ah! Thanks for tip, saved me a lot of time :) 👍

**Comment by kauefelipe** [comment]
Only change to:
`if (ResourceId != 0)
            {
                if (ResourceId <= 16777216)
                    uriString += "&maskedDefId=" + ResourceId.CalculateBaseId();
                else
                    uriString += "&definitionId=" + ResourceId;
            }`
