### ISSUE TITLE
.Net Core package ?

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#306]
Is there a way to .NetCore-Enable this project @trydis  ?

Thank's in advance

**Comment by trydis** [comment]
I think you should be able to use it as-is.

```
"frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
  }
```

I have thought about converting it to a [.NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) Library, but there are several things that make me want to postpone it. 

At the moment .NET Core projects use project.json, but will be replaced with [MSBuild-based .NET Core Tools](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/). These are not supported by VS 2015 and i guess many don't use Visual Studio 2017 RC, Visual Studio for Mac, Visual Studio Code or .NET Core CLI.

I would have to convert it like this:  msbuild (PCL) -> project.json (.NET Standard) -> msbuild (.NET Standard).

I will probably wait until the RTM of the MSBuild-based .NET Core tools are released, since I'm not using the toolkit, not that many are using it and few are willing to contribute to the project.

**Comment by DjTrilogic** [comment]
well thought !
