### ISSUE TITLE
Hamletic doubt

### ISSUE THREAD

**Issue by stojkovic76** [trydis/FIFA-Ultimate-Team-Toolkit#373]
Is better use a second account to use API and risk the ban when you move coins to the main or use directly the api in the first account?

On which of the two actions EA is more inflexible? (for example they send just a warn and wipe coins)

**Comment by KristianSv** [comment]
If you're careful and don't spam requests to EA, you can bot with your main account. Try with timers between 15 and 25 seconds. If you happen to get a captcha, wait for like a week and try again.
DISCLAIMER: Made 3m on my main account

**Comment by stojkovic76** [comment]
Thanks for the reply...in the mean while a make 1 milion but I receive a market ban on main and secondary account. Someone knows if they have a check for IP or consolle to avoid new account? I create a new one but I don't have the market unlocked also after 60 matches.

Yes the problem is that if you meet captcha many times during a day, also without insert it wrong after a while you will be banned.

**Comment by KristianSv** [comment]
That is completely true - you will get banned if captchas aren't solved every time (and first time) they're met.
You should keep in mind that you can only have two accounts granted web transfer access from one console. So one PS4 can "play up" two accounts, which can trade on the web app.

I can also tell you that they have just started IP-bans from today. And I've also had a lot of accounts transfer banned on the web app, because (I think) I made market requests which are not possible if not using a bot. Fx. searching for a resource id and team id in the same request (if a player is in two clubs but goes for different prices).

**Comment by stojkovic76** [comment]
Also consider that they often soft ban the market, you can buy but not sell for hours if the bot was running for too much time.

Anyway my bans are my fault because I overdone, trying to manage too many errors, if your program end after any kind of error and you check with web app and insert the captcha if necessary is very hard to receive a ban.

Someone know if my account will continue to keep the ban also the next year? Or each FIFA will grant a reset?

**Comment by goodspeed1392** [comment]
Maybe you should register new account for the next year?

**Comment by tringler** [comment]
Issue will be closed, because of inactivity and FIFA release change.
