### ISSUE TITLE
Parallelism Optimization Questions (ConfigureAwait(false))

### ISSUE THREAD

**Issue by DjTrilogic** [trydis/FIFA-Ultimate-Team-Toolkit#410]
Hello, 

I've been using this library since a few years, and in the meanwhile, i learned stuff about developping... And one thing of what i've learned is:

- It's recommended to use "ConfigureAwait(false)" whenever it's possible... (not to catch the context and stuff...)

So my 2 questions are:

- Is this rule lacking for a specific purpose ?
- Do you think it's an interesting optimization to wrap all the "await" stuff with a tailing "configureAwait(false)" ? If so, I can do that, and PR.

Thank's in advance

**Comment by trydis** [comment]
Hi.

I've been using it in [a lot](https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/search?q=ConfigureAwait&unscoped_q=ConfigureAwait) of places since the beginning, for that reason. That being said, I didn't enforce it with StyleCop rule(s) etc., since it was hard enough to get people to contribute at all.

Nowadays I barely play FIFA at all and haven't tried FUT in years, so I haven't maintained the code. I've been keeping an eye on the issues and it seems to work with some changes.

If you want to send a PR, that's great, I'll merge it 👍

**Comment by DjTrilogic** [comment]
I'll work on that anyway since I need a clean async system ...

I will PR once the work is done.

Thank's a lot @trydis.
